const IMG="https://image.tmdb.org/t/p/w500";let key=localStorage.getItem("tmdb_api_key")||"";let type="all";const $=s=>document.querySelector(s);const grid=$("#grid"),status=$("#status");
async function api(path){if(!key)throw Error("NO_KEY");const r=await fetch("https://api.themoviedb.org/3"+path,{headers:{Authorization:"Bearer "+key,accept:"application/json"}});if(!r.ok)throw Error("TMDB "+r.status);return r.json()}
function card(x){const title=x.title||x.name, date=(x.release_date||x.first_air_date||"").slice(0,4), img=x.poster_path?IMG+x.poster_path:"";return `<article class="card" data-id="${x.id}" data-kind="${x.media_type||type}"><div class="poster">${img?`<img loading="lazy" src="${img}" alt="">`:""}</div><h3>${title}</h3><div class="meta">★ ${(x.vote_average||0).toFixed(1)} · ${date||"—"}</div></article>`}
async function load(){if(!key){status.hidden=false;grid.innerHTML="";return}status.hidden=false;status.textContent="Loading…";try{let d=await api("/trending/"+(type==="all"?"all":type)+"/day");grid.innerHTML=d.results.map(x=>({...x,media_type:x.media_type||type})).map(card).join("");status.hidden=true}catch(e){status.hidden=false;status.textContent=e.message==="NO_KEY"?"Add your TMDB API key in Settings.":"Could not load TMDB data. Check your API key."}}
async function search(q){if(!q.trim())return load();if(!key){openSettings();return}status.hidden=false;status.textContent="Searching…";try{const d=await api("/search/multi?query="+encodeURIComponent(q)+"&include_adult=false&language=en-US&page=1");grid.innerHTML=d.results.filter(x=>x.media_type==="movie"||x.media_type==="tv").map(card).join("");status.hidden=true}catch(e){status.textContent="Search failed."}}
function openSettings(){$("#apiKey").value=key;$("#settings").classList.remove("hidden")}function closeModals(){document.querySelectorAll(".modal").forEach(x=>x.classList.add("hidden"))}
$("#settingsBtn").onclick=openSettings;$("#saveKey").onclick=()=>{key=$("#apiKey").value.trim();if(key)localStorage.setItem("tmdb_api_key",key);else localStorage.removeItem("tmdb_api_key");closeModals();load()};document.querySelectorAll("[data-close]").forEach(x=>x.onclick=closeModals);
$("#searchForm").onsubmit=e=>{e.preventDefault();search($("#searchInput").value)};$("#tabs").onclick=e=>{if(e.target.dataset.type){type=e.target.dataset.type;document.querySelectorAll(".tabs button").forEach(b=>b.classList.toggle("active",b===e.target));load()}};
grid.onclick=async e=>{const c=e.target.closest(".card");if(!c)return;try{const kind=c.dataset.kind==="tv"?"tv":"movie",d=await api("/"+kind+"/"+c.dataset.id+"?append_to_response=credits");$("#modalBody").innerHTML=`<div class="detail"><img src="${d.poster_path?IMG+d.poster_path:""}" alt=""><div><p class="eyebrow">${kind.toUpperCase()}</p><h2>${d.title||d.name}</h2><p class="muted">★ ${(d.vote_average||0).toFixed(1)} · ${(d.release_date||d.first_air_date||"").slice(0,4)}</p><p class="muted">${d.overview||"No overview available."}</p><p class="muted">${(d.genres||[]).map(g=>g.name).join(" · ")}</p><button class="primary" onclick="alert('Add your authorized video URL/player integration here.')">Watch authorized video</button></div></div>`;$("#modal").classList.remove("hidden")}catch{alert("Could not load details.")}};
$("#addVideoBtn").onclick=()=>alert("Use only video URLs you own or are licensed to embed. The player integration can be added here.");
load();